## Ensure GPG Key is imported
- name: Add GPG-Key for Elasticsearch from URL
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    validate_certs: no
  become: true

## Add YUM Repo
- name: Add Elastic 6.x yum repo
  yum_repository:
    name: elastic-6.x
    description: Elastic repository for 6.x packages
    file: elastic-6.x
    state: present
    enabled: yes
    proxy: http://{{proxy_host}}:{{proxy_port}}
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    repo_gpgcheck: yes
  become: true
