---
- hosts: all
  gather_facts: true
  tasks:
    - setup:
  roles:
    - AD-Common

- hosts: domain_controllers
  gather_facts: true
  tasks:
    - setup:
  roles:
    - AD-DomainServices

- hosts: workstations
  gather_facts: true
  tasks:
    - setup:
  roles:
    - AD-Workstation
