# host should be a member of domain ansible.lab; module will ensure the hostname is set
# and will use the passed credentials to join domain if necessary.
# If a reboot is required, the second task will trigger one and wait until the host is available.
- name: Join the lab domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: Administrator@{{domain}}
    domain_admin_password: "{{ default_password }}"
    #https://github.com/ansible/ansible/issues/57313#issuecomment-500615547
    #domain_ou_path: "OU=Workstations,OU=Machines,{{ldap_root}}"
    state: domain
  register: domain_state
  notify: reboot windows
