---
# handlers file
- name: reboot windows
  win_reboot:
    pre_reboot_delay: 5
    post_reboot_delay: 15
    reboot_timeout: 3600
    test_command: 'exit (Get-Service -Name WinRM).Status -ne "Running"'
