## Setup dns for ad-ds
- name: Set loopback addresses on all visible adapters (usually physical adapters that are in the Up state)
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - 127.0.0.1
