- name: Create employee group
  win_domain_group:
    name: Employees
    scope: global
    category: security
    protect: yes
    organizational_unit: "OU=Groups,OU=Accounts,OU={{org}},{{ldap_root}}"
    attributes:
      mail: "All-Employees@{{org_tld}}"

- name: Create service group
  win_domain_group:
    name: Service Accounts
    scope: global
    category: security
    protect: yes
    organizational_unit: "OU=Groups,OU=Accounts,OU={{org}},{{ldap_root}}"

- name: Create manager group
  win_domain_group:
    name: Managers
    scope: global
    category: security
    protect: yes
    organizational_unit: "OU=Groups,OU=Accounts,OU={{org}},{{ldap_root}}"
    attributes:
      mail: "All-Managers@{{org_tld}}"

- name: Create executive group
  win_domain_group:
    name: Executives
    scope: global
    category: security
    protect: yes
    organizational_unit: "OU=Groups,OU=Accounts,OU={{org}},{{ldap_root}}"
    attributes:
      mail: "All-Executives@{{org_tld}}"
  register: first_run

- name: Generate sample users
  win_domain_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    path: "OU=User Accounts,OU=Accounts,OU={{org}},{{ldap_root}}"
    groups_action: add
    groups: Employees
    state: present
    password_never_expires: yes
    user_cannot_change_password: yes
    firstname: "{{ item |capitalize }}"
    company: "{{org}}"
    street: 123 4th St.
    city: Jacksonville
    state_province: FL
    postal_code: 12345
    country: US
    description: "{{ profession |random }}"
    email: "{{ item }}@{{ org_tld }}"
    attributes:
        telephoneNumber: 555-123-4567
  register: user
  with_items:
     "{{ domain_users }}"
  when:
      first_run.changed

- name: Generate sample service accounts
  win_domain_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    path: "OU=Service Accounts,OU=Accounts,OU={{org}},{{ldap_root}}"
    groups_action: add
    groups: Service Accounts
    state: present
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "{{ item }} service account"
    email: "{{ item }}@{{ org_tld }}"
  register: user
  with_items:
     "{{ service_account_users }}"
  when:
      first_run.changed

# win_domain_group_membership requires ansible 2.8
- name: manage manager membership
  win_domain_group_membership:
    name: Managers
    members:
      - charlie
      - mike
      - heather
      - sam
    state: pure

- name: manage executive membership
  win_domain_group_membership:
    name: Executives
    members:
      - victor
      - xavier
    state: pure
