## Set hostname
- name: Set a hostname on the target
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_result
  notify: reboot windows

- name: force reboot on name change prior to AD role install
  meta: flush_handlers

## Setup dns for ad-ds
- name: Set loopback addresses on all visible adapters (usually physical adapters that are in the Up state)
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - 127.0.0.1

## Setup Firewall Rules
- name: fw - allow winrm inbound
  win_firewall_rule:
    name: "allow winrm"
    localport: 5985
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: fw - allow winrms inbound
  win_firewall_rule:
    name: "allow winrm(s)"
    localport: 5985
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: fw - allow rdp
  win_firewall_rule:
    name: "allow remote desktop"
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

  #########################################################################
  ## "win_firewall requires Windows Management Framework 5 or higher."
  #########################################################################
  # - name: Enable all firewalls
  # win_firewall:
  #   state: enabled
