---

all:

  children:

    austin:
      hosts:
        www[01:10].aus.tx.example.com:
        ns[01:10].aus.tx.example.com:

    dallas:
      hosts:
        www[01:10].dal.tx.example.com:
        ns[01:10].dal.tx.example.com:
