---
- name: Render GetCATrx.sh
  template:
    src: templates/etc/httpd/pki/GetCATrx.sh.j2
    dest: /etc/httpd/pki/GetCATrx.sh
  become: true
  notify:
    - restart service httpd

- name: Apply locked down perms
  file:
    path: /etc/httpd/pki/GetCATrx.sh
    owner: root
    group: apache
    mode: '0750'
  become: true
  notify:
    - restart service httpd
