- name: Set a hostname on the target
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_result
  notify: reboot windows

- name: force reboot on name changes
  meta: flush_handlers

- name: Create directory structure
  win_file:
    path: C:\ansible\
    state: directory

- name: copy sysmon config
  win_copy:
    src: files/sysmon.conf
    dest: C:\ansible\sysmon.conf

- name: install sysmon driver
  win_command: C:\ProgramData\chocolatey\bin\Sysmon.exe -i -accepteula
  register: sysmon_install
  ignore_errors: yes
 
- name: install sysmon config
  win_command: C:\ProgramData\chocolatey\bin\Sysmon.exe -c C:\ansible\sysmon.conf
  register: sysmon_config

## Render winlogbeat
- name: install winlogbeat config
  win_template: 
    src: templates/winlogbeat.yml.j2
    dest: C:\ProgramData\chocolatey\lib\winlogbeat\tools\winlogbeat.yml
  register: winlogbeat
  notify: restart winlogbeat

# Render filebeat
- name: install filebeat config
  win_template: 
    src: templates/filebeat.yml.j2
    dest: C:\ProgramData\chocolatey\lib\filebeat\tools\filebeat.yml
  register: winlogbeat
  notify: restart filebeat
