- name: Set a hostname on the target
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_result
  notify: reboot windows

- name: force reboot on name changes
  meta: flush_handlers

- name: enable rdp and ensure it is started
  win_service:
    name: TermService
    start_mode: auto
    state: started

- name: enable winrm and ensure it is started
  win_service:
    name: WinRM
    start_mode: auto
    state: started

- name: Create directory structure for ansible
  win_file:
    path: C:\ansible\
    state: directory

- name: Create directory structure for tokens
  win_file:
    path: C:\.tokens\
    state: directory
